micronaut:
  application:
    name: minimal-demo
  server:
    port: 8080

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    db-type: h2
    dialect: H2Dialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
